s = {
    "Manse": "Особняк",
    "Chews": "Жуёт",
    "Dirt-bike": "Мотоцикл для грязи",
    "Boss's": "Босса",
    "Decompose": "Разлагаться",
    "Mulch": "Мульча",
    "Non-alcoholic": "Безалкогольный",
    "Sparkling": "Игристый",
    "Hospitals": "Больницы",
    "Scottish-Mexican": "Шотландско-мексиканский",
    "Haggis": "Хаггис",
    "Enchiladas": "Энчиладас",
    "Stroll": "Прогулка",
    "Seating": "Рассадка",
    "Minnesotans": "Миннесотцы",
    "Aplomb": "Самообладание",
    "Biography": "Биография",
    "Grumbling": "Бормотание",
    "Manuscript": "Рукопись",
    "Roosevelt's": "Рузвельта",
    "Would-be": "Потенциальный",
    "Assassin's": "Убийцы",
    "Four-minute": "Четырёхминутный",
    "Brothers'": "Братьев",
    "Wills": "Завещания",
    "TR's": "ТР",
    "Juan": "Juan",
    "Spearheaded": "Возглавил",
    "Raged": "Буйствовал",
    "Archetype": "Архетип",
    "Politician": "Политик",
    "Incumbent": "Действующий",
    "Howard": "Howard",
    "Payne-Aldrich": "Пейн-Олдрич",
    "Tariff": "Тариф",
    "Skinny-dipping": "Купание нагишом",
    "Potomac": "Потомак",
    "Standoff": "Противостояние",
    "TR": "TR",
    "Stricken": "Поражённый",
    "Ray's": "Рэя",
    "Cover-up": "Сокрытие",
    "Strategically": "Стратегически",
    "Straps": "Ремни",
    "Snicker": "Хихиканье",
    "Parlor": "Гостиная",
    "Wh-What's": "Что",
    "Crouching": "Приседание",
    "Comma": "Запятая",
    "Blauman's": "Блаумана",
    "Haters'": "Ненавистников",
    "Capper": "Завершитель",
    "Oka": "Ока",
    "Curlies": "Кудряшки",
    "Collections": "Коллекции",
    "Terry": "Terry",
    "Gary's": "Гэри",
    "Crane-kick": "Удар журавля",
    "Confessed": "Признался",
    "Bri": "Бри",
    "Carl's": "Карла",
    "Mailing": "Почтовая рассылка",
    "Val": "Val",
    "Kilmer": "Kilmer",
    "Narrowly": "Едва",
    "Mandatory": "Обязательный",
    "Counseling": "Консультирование",
    "Bitterman": "Биттерман",
    "Drive-time": "Время вождения",
    "Humanities": "Гуманитарные науки",
    "Essays": "Эссе",
    "Har": "Хар",
    "Scooter's": "Скутера",
    "Tones": "Тона",
    "Rivers's": "Риверса",
    "Tripped": "Споткнулся",
    "Kudos": "Похвала",
    "Calming": "Успокаивающий",
    "Bard": "Бард",
    "Compose": "Составлять",
    "Vow-za": "Вау-обет",
    "Vow-erPoint": "Обет-ерПоинт",
    "Vow-erPoint--": "Обет-ерПоинт",
    "Unconditionally": "Безусловно",
    "Barney-shaped": "В форме Барни",
    "Hockey's": "Хоккея",
    "Consultants": "Консультанты",
    "Invowluntary": "Невольный обет",
    "Detector": "Детектор",
    "Square-foot": "Квадратный фут",
    "Bittersweet": "Горько-сладкий",
    "Pease": "Пиз",
    "Beech": "Бук",
    "Friendster": "Friendster",
    "Magic's": "Магии",
    "Deuces": "Двойки",
    "Blackhawks": "Блэкхокс",
    "Nonsensical": "Бессмысленный",
    "Six-year": "Шестилетний",
    "Double-flusher": "Двойной смыв",
    "Messier": "Мессье",
    "Updated": "Обновлённый",
    "Weird-looking": "Странно выглядящий",
    "Maybelline": "Maybelline",
    "Spew": "Извергать",
    "Petitioning": "Петиция",
    "McCartney": "McCartney",
    "Secondary": "Вторичный",
    "Updating": "Обновление",
    "Sprinting": "Спринт",
    "Downs": "Спады",
    "Twisting": "Скручивание",
    "Roxanne": "Roxanne",
    "When'd": "Когда",
    "Consists": "Состоит",
    "Upwar": "Вверх",
    "Venkman": "Венкман",
    "Pattering": "Стук",
    "G-Go": "Иди",
    "F-feel": "Чувствую",
    "Hot-air": "Горячий воздух",
    "Stagecoach": "Дилижанс",
    "Caracas": "Каракас",
    "Petersburg": "Петербург",
    "Moat": "Ров",
    "Peeked": "Подглядел",
    "Jousting": "Рыцарский турнир",
    "Reasonably": "Разумно",
    "Upscale": "Высококлассный",
    "W-what": "Что",
    "Three-year": "Трёхлетний",
    "Cleanups": "Уборки",
    "Ahab": "Ахаб",
    "Thinkin'": "Думаю",
    "Officer's": "Офицера",
    "Charmingly": "Очаровательно",
    "Retro": "Ретро",
    "Pumpkin's": "Тыквы",
    "Splits": "Расколы",
    "Midair": "В воздухе",
    "Roth": "Roth",
    "Allowing": "Разрешение",
    "Sputtering": "Плевки",
    "Awakened": "Пробуждённый",
    "Four-and-a-half": "Четыре с половиной",
    "Enduring": "Прочный",
    "Straightens": "Выпрямляет",
    "A-plow": "Плуг",
    "Judge-y": "Осуждающий",
    "Robot's": "Робота",
    "Forties": "Сороковые",
    "Mentions": "Упоминания",
    "Y-You": "Ты",
    "Asterisk": "Звёздочка",
    "Monthly": "Ежемесячный",
    "Classicism": "Классицизм",
    "Sighting": "Наблюдение",
    "Yeti": "Йети",
    "Aloof": "Отстранённый",
    "Abominable": "Отвратительный",
    "Snowman": "Снежный человек",
    "Ex-husband's": "Бывшего мужа",
    "Urp": "Отрыжка",
    "Ellie": "Ellie",
    "Statute": "Устав",
    "Limitations": "Ограничения",
    "Re-propose": "Повторно предложить",
    "RSVP'd": "Подтверждённый",
    "Endurance": "Выносливость",
    "Pang": "Укол",
    "Cindy's": "Синди",
    "McConnell": "McConnell",
    "Accompanied": "Сопровождаемый",
    "Baskets": "Корзины",
    "Beverages": "Напитки",
    "Bikes": "Велосипеды",
    "Containers": "Контейнеры",
    "Cooperation": "Сотрудничество",
    "Courts": "Корты",
    "Damaging": "Повреждающий",
    "Firepit": "Кострище",
    "Leaseholder": "Арендатор",
    "Leasing": "Аренда",
    "Nets": "Сети",
    "Rollerblades": "Роликовые коньки",
    "Spaces": "Пространства",
    "Supervised": "Под наблюдением",
    "Automation": "Автоматизация",
    "Docker": "Докер",
    "Engineer": "Инженер",
    "Git": "Гит",
    "Infrastructure": "Инфраструктура",
    "Jul": "Июль",
    "Lifecycle": "Жизненный цикл",
    "Maintaining": "Поддержание",
    "Programming": "Программирование",
    "Pytest": "Pytest",  # Proper noun, no translation
    "Qa": "Контроль качества",
    "Repository": "Репозиторий",
    "Sd": "Сан-Диего",  # Assuming abbreviation for San Diego
    "Sdet": "Инженер по тестированию",
    "Versed": "Сведущий",
    "Availability": "Доступность",
    "Busier": "Более загруженный",
    "Cant": "Не может",
    "Crossregion": "Межрегиональный",
    "Dash": "Даш",  # Kept as is, DoorDash-specific term
    "Dasher": "Дашер",  # DoorDash-specific term
    "Dashers": "Дашеры",  # Plural of Dasher
    "Dashing": "Дашинг",  # DoorDash-specific term
    "Dependency": "Зависимость",
    "Desired": "Желаемый",
    "Dispatching": "Диспетчеризация",
    "Divides": "Разделяет",
    "Doordash": "DoorDash",  # Brand name, no translation
    "Doordashs": "DoorDash",  # Brand name, possessive form
    "Enabled": "Включённый",
    "Geographic": "Географический",
    "Glitches": "Сбои",
    "Gps": "GPS",  # Acronym, no translation
    "Greenlight": "Greenlight",  # Uber-specific term
    "Hubs": "Хабы",
    "Inquiry": "Запрос",
    "Instructions": "Инструкции",
    "Ios": "iOS",  # Platform name, no translation
    "Isnt": "Не является",
    "Languageen_us": "Английский (США)",  # Language code
    "Locationbased": "Базируемый на местоположении",
    "Logged": "Вошёл",
    "Manual": "Ручной",
    "Naperville": "Нейпервилл",  # Proper noun, transliterated
    "Platforms": "Платформы",
    "Prioritize": "Приоритизировать",
    "Prompt": "Подсказка",
    "Restarting": "Перезапуск",
    "Restricts": "Ограничивает",
    "Screenshots": "Скриншоты",
    "Troubleshooting": "Устранение неполадок",
    "Uber": "Uber",  # Brand name, no translation
    "Ubers": "Uber",  # Brand name, possessive form
    "Varies": "Варьируется",
    "Verify": "Проверить",
    "Visuals": "Визуалы",
    "Youll": "Вы будете",
    "Yourre": "Вы есть",
    "Ambiguous": "Неоднозначный",
    "Api": "Эй Пи Ай",
    "Attempting": "Попытка",
    "Classification": "Классификация",
    "Computation": "Вычисление",
    "Documentation": "Документация",
    "Efficacy": "Эффективность",
    "Emphasizing": "Подчеркивание",
    "Evaluating": "Оценка",
    "Experimenting": "Экспериментирование",
    "Extraction": "Извлечение",
    "Gemma": "Гемма",
    "Hinder": "Мешать",
    "Inputs": "Входы",
    "Iterative": "Итеративный",
    "Model’s": "Модели",
    "Modalities": "Модальности",
    "Nucleus": "Ядро",
    "Outputs": "Выходы",
    "Potentially": "Потенциально",
    "Probabilities": "Вероятности",
    "Prompted": "Подсказанный",
    "Restive": "Неспокойный",
    "Restriction": "Ограничение",
    "Scientist": "Ученый",
    "Selection": "Выбор",
    "Softmax": "Софтмакс",
    "Stylistically": "Стилистически",
    "Succinct": "Краткий",
    "Summarization": "Обобщение",
    "Textual": "Текстовый",
    "Topk": "Топ-К",
    "Topp": "Топ-П",
    "Wordchoice": "Выбор слова",
    "Accordingly": "Соответственно",
    "Additionally": "Дополнительно",
    "Aficionado": "Знаток",
    "Ai": "ИИ",
    "Alleys": "Аллеи",
    "Allied": "Союзный",
    "Allows": "Позволяет",
    "Ambushed": "Засада",
    "Artsy-Fartsy": "Художественный",
    "Aspects": "Аспекты",
    "Assigning": "Назначение",
    "Bask": "Нежиться",
    "Biases": "Предубеждения",
    "Blueprint": "Чертеж",
    "Boggle": "Смущать",
    "Broader": "Ширший",
    "Cabinets": "Шкафы",
    "Capabilities": "Возможности",
    "Classify": "Классифицировать",
    "Close-Quarters": "Близкий контакт",
    "Codebase": "Кодовая база",
    "Combine": "Комбинировать",
    "Complexity": "Сложность",
    "Confrontational": "Конфронтационный",
    "Contextual": "Контекстуальный",
    "Conversely": "Наоборот",
    "Corridors": "Коридоры",
    "Creativity": "Креативность",
    "Criteria": "Критерии",
    "Critically": "Критически",
    "Cumulative": "Кумулятивный",
    "Cunning": "Хитрый",
    "Cybernetically": "Кибернетически",
    "Cyberpunk": "Киберпанк",
    "Datetime": "Дата и время",
    "Deep-Sea": "Глубоководный",
    "Defining": "Определение",
    "Delve": "Вникать",
    "Dense": "Плотный",
    "Descriptive": "Описательный",
    "Desolate": "Пустынный",
    "Dilapiated": "Заброшенный",
    "Disable": "Отключить",
    "Disadvantages": "Недостатки",
    "Dizzying": "Головокружительный",
    "Drowned": "Утопленный",
    "Effectiveness": "Эффективность",
    "Elite": "Элитный",
    "Encourages": "Поощряет",
    "Ensuring": "Обеспечение",
    "Environments": "Среда",
    "Etc": "И т.д.",
    "Evolving": "Эволюционирующий",
    "Exceed": "Превышать",
    "Expertise": "Экспертиза",
    "Fabulousness": "Великолепие",
    "Facility": "Объект",
    "Faction": "Фракция",
    "Few-Shot": "Малошот",
    "Finetune": "Точная настройка",
    "Flooded": "Затопленный",
    "Gemini-Pro": "Джемини-Про",
    "Grappling": "Схватка",
    "Half-Half": "Половина-на-половину",
    "Hallucinations": "Галлюцинации",
    "Highlighting": "Выделение",
    "Hordes": "Орды",
    "Humorous": "Юмористический",
    "Imitate": "Имитировать",
    "Impacts": "Воздействия",
    "Implementation": "Реализация",
    "Implementations": "Реализации",
    "Insightful": "Проницательный",
    "Interact": "Взаимодействовать",
    "Interactions": "Взаимодействия",
    "Interpretability": "Интерпретируемость",
    "Intuitive": "Интуитивный",
    "Iterations": "Итерации",
    "Json": "Джейсон",
    "Kandinsky": "Кандинский",
    "Limitation": "Ограничение",
    "Lurk": "Скрываться",
    "Machinery": "Механизм",
    "Manually": "Вручную",
    "Maze": "Лабиринт",
    "Mitigate": "Смягчить",
    "Monotonous": "Монотонный",
    "Murky": "Мутный",
    "Mutated": "Мутированный",
    "Neon-Lit": "Неоново-освещенный",
    "Nonzero": "Ненулевой",
    "Nuances": "Нюансы",
    "One-Shot": "Одношот",
    "Optimal": "Оптимальный",
    "Overarching": "Всеобъемлющий",
    "Overly": "Слишком",
    "Paragraph": "Параграф",
    "Pixel": "Пиксель",
    "Post-Apocalyptic": "Постапокалиптический",
    "Predators": "Хищники",
    "Predict": "Предсказывать",
    "Predicted": "Предсказанный",
    "Provides": "Предоставляет",
    "Pulsating": "Пульсирующий",
    "Relay": "Реле",
    "Relentless": "Неумолимый",
    "Rembrandt": "Рембрандт",
    "Repetition": "Повторение",
    "Requirements": "Требования",
    "Requiring": "Требующий",
    "Resourcefulness": "Находчивость",
    "Rijksmuseum": "Рейксмузеум",
    "Robust": "Надежный",
    "Robustness": "Надежность",
    "Roots": "Корни",
    "Sampled": "Отобранный",
    "Seamless": "Бесшовный",
    "Selects": "Выбирает",
    "Showcasing": "Демонстрация",
    "Simplest": "Простейший",
    "Soldiers": "Солдаты",
    "Solving": "Решение",
    "Spacecraft": "Космический корабль",
    "Specify": "Указать",
    "Squad": "Отряд",
    "Starry": "Звездный",
    "Stealth": "Скрытность",
    "Step-Back": "Шаг назад",
    "Storyline": "Сюжетная линия",
    "Structured": "Структурированный",
    "Styles": "Стили",
    "Sunflowers": "Подсолнухи",
    "Tasked": "Порученный",
    "Testament": "Свидетельство",
    "Top-K": "Топ-К",
    "Top-P": "Топ-П",
    "Toxicity": "Токсичность",
    "Tracing": "Отслеживание",
    "Translating": "Перевод",
    "Treacherous": "Коварный",
    "Uncharted": "Неизведанный",
    "Unchecked": "Непроверенный",
    "Underwater": "Подводный",
    "Underlying": "Базовый",
    "Unhelpful": "Бесполезный",
    "Uppercase": "Верхний регистр",
    "Utilizing": "Использование",
    "Venturing": "Риск",
    "Vessel": "Сосуд",
    "Window-Shop": "Витринный шопинг",
    "World-Renowned": "Всемирно известный",
    "Writings": "Писания",
    "Zero-Gravity": "Нулевая гравитация",
    "Zero-Shot": "Нулевой шот",
    "Zombie-Infested": "Зараженный зомби",
    "Assess": "Оценивать",
    "Assumptions": "Предположения",
    "Coherence": "Согласованность",
    "Deface": "Портить",
    "Enable": "Включить",
    "Github": "Гитхаб",
    "Googlecloudplatform": "ГуглКлаудПлатформ",
    "Hetfield": "Хетфилд",
    "Improves": "Улучшает",
    "Inv0k3d": "Вызванный",
    "Java": "Джава",
    "Javascript": "Джаваскрипт",
    "Langchain": "Лангчейн",
    "Lars": "Ларс",
    "Limiting": "Ограничение",
    "Lani": "Лани",
    "Malicious": "Вредоносный",
    "Mapping": "Сопоставление",
    "Mathematical": "Математический",
    "Nlp": "НЛП",
    "Observations": "Наблюдения",
    "Paths": "Пути",
    "Performs": "Выполняет",
    "Perspectives": "Перспективы",
    "Plugins": "Плагины",
    "Pseudo": "Псевдо",
    "Python": "Питон",
    "Resend": "Отправить повторно",
    "Screenshot": "Скриншот",
    "Script": "Скрипт",
    "Selecting": "Выбор",
    "Serpapi": "Серпапи",
    "Snippet": "Фрагмент",
    "Trujillo": "Трухильо",
    "Ulrich": "Ульрих",
    "Unverified": "Непроверенный",
    "Verbal": "Вербальный",
    "Vertexai": "ВертексАй",
    "Voting": "Голосование",
    "Wordpress": "Вордпресс",
    "Xyz": "ЭксВайЗет",
    "Alleviates": "Облегчает",
    "Automate": "Автоматизировать",
    "Bleu": "Блю",
    "Coding": "Кодирование",
    "Contents": "Содержимое",
    "Developer": "Разработчик",
    "Enhances": "Улучшает",
    "Evaluate": "Оценивать",
    "Filename": "Имя файла",
    "Indenting": "Отступ",
    "Merchandise": "Товар",
    "Renamed": "Переименованный",
    "Renaming": "Переименование",
    "Reusable": "Многоразовый",
    "Rouge": "Руж",
    "T-Shirt": "Футболка",
    "Tweak": "Настройка",
    "Ui": "Юай",
    "Webshop": "Веб-магазин",
    "Adapt": "Адаптировать",
    "Applications": "Приложения",
    "Attributes": "Атрибуты",
    "Bluetooth": "Блютуз",
    "Categorize": "Категоризировать",
    "Components": "Компоненты",
    "Concise": "Краткий",
    "Constraints": "Ограничения",
    "Debugging": "Отладка",
    "Dreamcast": "Дримкаст",
    "E-Commerce": "Электронная коммерция",
    "Electronics": "Электроника",
    "Formats": "Форматы",
    "Formatting": "Форматирование",
    "Hardcoding": "Жесткое кодирование",
    "Harmful": "Вредный",
    "Hyphen": "Дефис",
    "Integrating": "Интеграция",
    "Leverage": "Использовать",
    "Organize": "Организовать",
    "Overfitting": "Переобучение",
    "Predicts": "Предсказывает",
    "Prefix": "Префикс",
    "Prepend": "Добавить в начало",
    "Preprocessing": "Предобработка",
    "Readable": "Читаемый",
    "Relying": "Опираться",
    "Repeating": "Повторение",
    "Requirement": "Требование",
    "Reviewing": "Обзор",
    "Schema": "Схема",
    "Schemas": "Схемы",
    "Simplicity": "Простота",
    "Six": "Шесть",
    "Specificity": "Специфичность",
    "Timestamp": "Метка времени",
    "Traceback": "Трассировка",
    "Unseen": "Невидимый",
    "Urgency": "Срочность",
    "Variable": "Переменная",
    "Variance": "Дисперсия",
    "Verbs": "Глаголы",
    "Augment": "Увеличивать",
    "Bilingual": "Двуязычный",
    "Deliberate": "Обдуманный",
    "Discusses": "Обсуждает",
    "Endnotes": "Концевые сноски",
    "Generalize": "Обобщать",
    "Hyperlink": "Гиперссылка",
    "Inserted": "Вставленный",
    "Iteration": "Итерация",
    "Learners": "Обучающиеся",
    "Rag": "Раг",
    "Refining": "Уточнение",
    "Rerunning": "Перезапуск",
    "Retrieval": "Извлечение",
    "Rewriting": "Переписывание",
    "Synergizing": "Синергия",
    "Template": "Шаблон",

}