s = {
    "Manse": "Особняк",
    "Chews": "Жуёт",
    "Dirt-bike": "Мотоцикл для грязи",
    "Boss's": "Босса",
    "Decompose": "Разлагаться",
    "Mulch": "Мульча",
    "Non-alcoholic": "Безалкогольный",
    "Sparkling": "Игристый",
    "Hospitals": "Больницы",
    "Scottish-Mexican": "Шотландско-мексиканский",
    "Haggis": "Хаггис",
    "Enchiladas": "Энчиладас",
    "Stroll": "Прогулка",
    "Seating": "Рассадка",
    "Minnesotans": "Миннесотцы",
    "Aplomb": "Самообладание",
    "Biography": "Биография",
    "Grumbling": "Бормотание",
    "Manuscript": "Рукопись",
    "Roosevelt's": "Рузвельта",
    "Would-be": "Потенциальный",
    "Assassin's": "Убийцы",
    "Four-minute": "Четырёхминутный",
    "Brothers'": "Братьев",
    "Wills": "Завещания",
    "TR's": "ТР",
    "Juan": "Juan",
    "Spearheaded": "Возглавил",
    "Raged": "Буйствовал",
    "Archetype": "Архетип",
    "Politician": "Политик",
    "Incumbent": "Действующий",
    "Howard": "Howard",
    "Payne-Aldrich": "Пейн-Олдрич",
    "Tariff": "Тариф",
    "Skinny-dipping": "Купание нагишом",
    "Potomac": "Потомак",
    "Standoff": "Противостояние",
    "TR": "TR",
    "Stricken": "Поражённый",
    "Ray's": "Рэя",
    "Cover-up": "Сокрытие",
    "Strategically": "Стратегически",
    "Straps": "Ремни",
    "Snicker": "Хихиканье",
    "Parlor": "Гостиная",
    "Wh-What's": "Что",
    "Crouching": "Приседание",
    "Comma": "Запятая",
    "Blauman's": "Блаумана",
    "Haters'": "Ненавистников",
    "Capper": "Завершитель",
    "Oka": "Ока",
    "Curlies": "Кудряшки",
    "Collections": "Коллекции",
    "Terry": "Terry",
    "Gary's": "Гэри",
    "Crane-kick": "Удар журавля",
    "Confessed": "Признался",
    "Bri": "Бри",
    "Carl's": "Карла",
    "Mailing": "Почтовая рассылка",
    "Val": "Val",
    "Kilmer": "Kilmer",
    "Narrowly": "Едва",
    "Mandatory": "Обязательный",
    "Counseling": "Консультирование",
    "Bitterman": "Биттерман",
    "Drive-time": "Время вождения",
    "Humanities": "Гуманитарные науки",
    "Essays": "Эссе",
    "Har": "Хар",
    "Scooter's": "Скутера",
    "Tones": "Тона",
    "Rivers's": "Риверса",
    "Tripped": "Споткнулся",
    "Kudos": "Похвала",
    "Calming": "Успокаивающий",
    "Bard": "Бард",
    "Compose": "Составлять",
    "Vow-za": "Вау-обет",
    "Vow-erPoint": "Обет-ерПоинт",
    "Vow-erPoint--": "Обет-ерПоинт",
    "Unconditionally": "Безусловно",
    "Barney-shaped": "В форме Барни",
    "Hockey's": "Хоккея",
    "Consultants": "Консультанты",
    "Invowluntary": "Невольный обет",
    "Detector": "Детектор",
    "Square-foot": "Квадратный фут",
    "Bittersweet": "Горько-сладкий",
    "Pease": "Пиз",
    "Beech": "Бук",
    "Friendster": "Friendster",
    "Magic's": "Магии",
    "Deuces": "Двойки",
    "Blackhawks": "Блэкхокс",
    "Nonsensical": "Бессмысленный",
    "Six-year": "Шестилетний",
    "Double-flusher": "Двойной смыв",
    "Messier": "Мессье",
    "Updated": "Обновлённый",
    "Weird-looking": "Странно выглядящий",
    "Maybelline": "Maybelline",
    "Spew": "Извергать",
    "Petitioning": "Петиция",
    "McCartney": "McCartney",
    "Secondary": "Вторичный",
    "Updating": "Обновление",
    "Sprinting": "Спринт",
    "Downs": "Спады",
    "Twisting": "Скручивание",
    "Roxanne": "Roxanne",
    "When'd": "Когда",
    "Consists": "Состоит",
    "Upwar": "Вверх",
    "Venkman": "Венкман",
    "Pattering": "Стук",
    "G-Go": "Иди",
    "F-feel": "Чувствую",
    "Hot-air": "Горячий воздух",
    "Stagecoach": "Дилижанс",
    "Caracas": "Каракас",
    "Petersburg": "Петербург",
    "Moat": "Ров",
    "Peeked": "Подглядел",
    "Jousting": "Рыцарский турнир",
    "Reasonably": "Разумно",
    "Upscale": "Высококлассный",
    "W-what": "Что",
    "Three-year": "Трёхлетний",
    "Cleanups": "Уборки",
    "Ahab": "Ахаб",
    "Thinkin'": "Думаю",
    "Officer's": "Офицера",
    "Charmingly": "Очаровательно",
    "Retro": "Ретро",
    "Pumpkin's": "Тыквы",
    "Splits": "Расколы",
    "Midair": "В воздухе",
    "Roth": "Roth",
    "Allowing": "Разрешение",
    "Sputtering": "Плевки",
    "Awakened": "Пробуждённый",
    "Four-and-a-half": "Четыре с половиной",
    "Enduring": "Прочный",
    "Straightens": "Выпрямляет",
    "A-plow": "Плуг",
    "Judge-y": "Осуждающий",
    "Robot's": "Робота",
    "Forties": "Сороковые",
    "Mentions": "Упоминания",
    "Y-You": "Ты",
    "Asterisk": "Звёздочка",
    "Monthly": "Ежемесячный",
    "Classicism": "Классицизм",
    "Sighting": "Наблюдение",
    "Yeti": "Йети",
    "Aloof": "Отстранённый",
    "Abominable": "Отвратительный",
    "Snowman": "Снежный человек",
    "Ex-husband's": "Бывшего мужа",
    "Urp": "Отрыжка",
    "Ellie": "Ellie",
    "Statute": "Устав",
    "Limitations": "Ограничения",
    "Re-propose": "Повторно предложить",
    "RSVP'd": "Подтверждённый",
    "Endurance": "Выносливость",
    "Pang": "Укол",
    "Cindy's": "Синди",
    "McConnell": "McConnell",
    "Accompanied": "Сопровождаемый",
    "Baskets": "Корзины",
    "Beverages": "Напитки",
    "Bikes": "Велосипеды",
    "Containers": "Контейнеры",
    "Cooperation": "Сотрудничество",
    "Courts": "Корты",
    "Damaging": "Повреждающий",
    "Firepit": "Кострище",
    "Leaseholder": "Арендатор",
    "Leasing": "Аренда",
    "Nets": "Сети",
    "Rollerblades": "Роликовые коньки",
    "Spaces": "Пространства",
    "Supervised": "Под наблюдением",
    "Automation": "Автоматизация",
    "Docker": "Докер",
    "Engineer": "Инженер",
    "Git": "Гит",
    "Infrastructure": "Инфраструктура",
    "Jul": "Июль",
    "Lifecycle": "Жизненный цикл",
    "Maintaining": "Поддержание",
    "Programming": "Программирование",
    "Pytest": "Pytest",  # Proper noun, no translation
    "Qa": "Контроль качества",
    "Repository": "Репозиторий",
    "Sd": "Сан-Диего",  # Assuming abbreviation for San Diego
    "Sdet": "Инженер по тестированию",
    "Versed": "Сведущий",
    "Availability": "Доступность",
    "Busier": "Более загруженный",
    "Cant": "Не может",
    "Crossregion": "Межрегиональный",
    "Dash": "Даш",  # Kept as is, DoorDash-specific term
    "Dasher": "Дашер",  # DoorDash-specific term
    "Dashers": "Дашеры",  # Plural of Dasher
    "Dashing": "Дашинг",  # DoorDash-specific term
    "Dependency": "Зависимость",
    "Desired": "Желаемый",
    "Dispatching": "Диспетчеризация",
    "Divides": "Разделяет",
    "Doordash": "DoorDash",  # Brand name, no translation
    "Doordashs": "DoorDash",  # Brand name, possessive form
    "Enabled": "Включённый",
    "Geographic": "Географический",
    "Glitches": "Сбои",
    "Gps": "GPS",  # Acronym, no translation
    "Greenlight": "Greenlight",  # Uber-specific term
    "Hubs": "Хабы",
    "Inquiry": "Запрос",
    "Instructions": "Инструкции",
    "Ios": "iOS",  # Platform name, no translation
    "Isnt": "Не является",
    "Languageen_us": "Английский (США)",  # Language code
    "Locationbased": "Базируемый на местоположении",
    "Logged": "Вошёл",
    "Manual": "Ручной",
    "Naperville": "Нейпервилл",  # Proper noun, transliterated
    "Platforms": "Платформы",
    "Prioritize": "Приоритизировать",
    "Prompt": "Подсказка",
    "Restarting": "Перезапуск",
    "Restricts": "Ограничивает",
    "Screenshots": "Скриншоты",
    "Troubleshooting": "Устранение неполадок",
    "Uber": "Uber",  # Brand name, no translation
    "Ubers": "Uber",  # Brand name, possessive form
    "Varies": "Варьируется",
    "Verify": "Проверить",
    "Visuals": "Визуалы",
    "Youll": "Вы будете",
    "Yourre": "Вы есть",

}