h_vocabulary = {
"Although": "– хотя",
"Even though": "– даже если, хотя",
"Even if": "– даже если",
"Inasmuch as": "– поскольку, в той мере в какой",
"Insofar as": "– поскольку, насколько",
"Provided (that)": "– при условии, что",
"Providing (that)": "– при условии, что",
"Unless": "– если не, пока не",
"Lest": "– чтобы не (устар.)",
"Whereas": "– в то время как",
"Whereupon": "– после чего",
"Whereby": "– посредством чего, благодаря чему",
"Notwithstanding (that)": "– несмотря на то, что",
"In order that": "– для того чтобы",
"So that": "– чтобы",
"So long as": "– пока, при условии что",
"As long as": "– пока, при условии что",
"Now that": "– теперь когда",
"In case (that)": "– в случае, если",
"In the event (that)": "– в случае если",
"For fear that": "– из страха, что; чтобы не",
"No matter how": "– как бы ни",
"No matter what": "– что бы ни",
"Whichever": "– который бы ни",
"Whenever": "– когда бы ни",
}