h_vocabulary = {
"Adamantly": "– категорически",
"Adeptly": "– умело",
"Ambiguously": "– двусмысленно",
"Apprehensively": "– с опаской",
"Ardently": "– горячо, страстно",
"Assiduously": "– усердно, прилежно",
"Astutely": "– проницательно",
"Blatantly": "– откровенно, явно",
"Conspicuously": "– заметно",
"Cordially": "– сердечно",
"Deftly": "– ловко, искусно",
"Diligently": "– прилежно",
"Eloquently": "– красноречиво",
"Eminently": "– в высшей степени",
"Equitably": "– справедливо",
"Explicitly": "– открыто, ясно",
"Exquisitely": "– изысканно",
"Incessantly": "– непрерывно",
"Indelibly": "– неизгладимо",
"Intrinsically": "– по сути, внутренне",
"Meticulously": "– дотошно, скрупулезно",
"Obtrusively": "– навязчиво",
"Overtly": "– явно, открыто",
"Perennially": "– постоянно, из года в год",
"Unassumingly": "– скромно, непритязательно",

}