e_vocabulary = {
"To go": "– идти / ходить / ехать (depending on mode of travel)",
"To come": "– приходить / приезжать",
"To see": "– видеть",
"To look": "– смотреть",
"To hear": "– слышать",
"To listen": "– слушать",
"To eat": "– есть",
"To drink": "– пить",
"To read": "– читать",
"To write": "– писать",
"To speak": "– говорить",
"To say": "– сказать",
"To do": "– делать",
"To make": "– делать / создавать",
"To know": "– знать",
"To think": "– думать",
"To understand": "– понимать",
"To take": "– брать",
"To give": "– давать",
"To work": "– работать",
}