e_vocabulary = {
"I": "– я",
"You": "(singular informal) – ты ||  (formal or plural) – вы || (singular informal) – тебя (acc.), тебе (dat.) || (formal or plural) – вас (acc.), вам (dat.)",
"He": "– он",
"She": "– она",
"It": "– оно (or simply “он/она/оно” depending on noun gender) || его/её (depends on the noun’s gender)",
"We": "– мы",
"They": "– они",
"Me": "– меня (acc.), мне (dat.)",
"Him": "– его (acc.), ему (dat.)",
"Her": "– её (acc.), ей (dat.) || её",
"Us": "– нас (acc.), нам (dat.)",
"Them": "– их (acc.), им (dat.)",
"My": "– мой (m.), моя (f.), моё (n.), мои (pl.)",
"Your": "(formal/plural) – ваш, ваша, ваше, ваши || (singular informal) – твой, твоя, твоё, твои",
"His": "– его",
"Its": "– его/её (depending on grammatical gender)",
"Our": "– наш, наша, наше, наши",
"Their": "– их",
"Mine": "– мой, моя, моё, мои (used as a noun: “мой” can stand for “mine”)",
"Yours": "(singular informal) – твой, твоя, твоё, твои (similarly used) || (formal/plural) – ваш, ваша, ваше, ваши",
"Hers": "– её",
"Ours": "– наш, наша, наше, наши",
"Theirs": "– их",
"Myself": "– (я) сам/сама себя",
"Yourself": "(singular informal) – (ты) сам/сама себя || (formal/plural) – (вы) сами себя",
"Himself": "– (он) сам себя",
"Herself": "– (она) сама себя",
"Itself": "– (оно) само себя",
"Ourselves": "– (мы) сами себя",
"Themselves": "– (они) сами себя",
"This": "– этот (m.), эта (f.), это (n.), эти (pl.)",
"That": "– тот (m.), та (f.), то (n.), те (pl.) || который (often omitted in Russian)",
"These": "– эти",
"Those": "– те",
"What": "– что",
"Which": "– который (as a question: “который?”, “какой?”) || который",
"Whose": "– чей (m.), чья (f.), чьё (n.), чьи (pl.) || чей (often rendered as которого/чей in relative clauses)",
"Whom": "– кого (object form of кто) || кого (or которого)",
"What kind": "– какой (m.), какая (f.), какое (n.), какие (pl.)",
"Who": "– кто (often translated as который or кто depending on usage) || кто",
"What (meaning “that which”)": "– то, что",
"Someone / Somebody": "– кто-то",
"Something": "– что-то",
"Somewhere": "– где-то",
"Anyone / Anybody": "– кто-нибудь",
"Anything": "– что-нибудь",
"Anywhere": "– где-нибудь",
"No one / Nobody": "– никто",
"Nothing": "– ничего",
"Nowhere": "– нигде",
"Everyone / Everybody": "– все",
"Everything": "– всё",
"Everywhere": "– везде",
"Each": "– каждый (m.), каждая (f.), каждое (n.), каждые (pl.)",
"Either": "– либо один (из двух), любой (из двух)",
"Neither": "– ни тот, ни другой",
"Each other": "– друг друга",
"One another": "– друг друга",

}

# its all of them