e_vocabulary = {
"Quickly": "– быстро",
"Slowly": "– медленно",
"Carefully": "– осторожно",
"Quietly": "– тихо",
"Loudly": "– громко",
"Easily": "– легко",
"Happily": "– счастливо",
"Sadly": "– грустно",
"Beautifully": "– красиво",
"Badly": "– плохо",
"Often": "– часто",
"Rarely": "– редко",
"Always": "– всегда",
"Never": "– никогда",
"Sometimes": "– иногда",
"Immediately": "– немедленно",
"Suddenly": "– внезапно",
"Politely": "– вежливо",
"Rudely": "– грубо",
"Honestly": "– честно",

}